# Generated by Django 3.2.3 on 2021-05-30 05:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20210530_1139'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='oderPlaced',
            new_name='OrderPlaced',
        ),
    ]
